"use client"

import { useState } from "react"
import { api } from "@/convex/_generated/api"
import {
  generatedEventDataAtom,
  isGeneratingAtom,
  setGeneratedEventData,
  setIsGenerating,
  setWizardStep,
  updateWizardData,
} from "@/features/events/eventWizard"
import { useAction } from "convex/react"
import { useAtom } from "jotai"
import { ArrowRight, Loader2, RefreshCw, SkipForward, Sparkles } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"

const PROMPT_MIN_LENGTH = 20
const PROMPT_MAX_LENGTH = 400

export function EventWizardAiPromptStep() {
  const [promptText, setPromptText] = useState("")
  const [generationError, setGenerationError] = useState<string | null>(null)
  const [generatedData] = useAtom(generatedEventDataAtom)
  const [isGenerating] = useAtom(isGeneratingAtom)
  const [, dispatchSetIsGenerating] = useAtom(setIsGenerating)
  const [, dispatchSetGeneratedData] = useAtom(setGeneratedEventData)
  const [, dispatchSetWizardStep] = useAtom(setWizardStep)
  const [, dispatchUpdateWizardData] = useAtom(updateWizardData)

  const generateFromPrompt = useAction(api.events.generateFromPrompt)

  const charCount = promptText.length
  const isPromptValid = charCount >= PROMPT_MIN_LENGTH && charCount <= PROMPT_MAX_LENGTH

  async function handleGenerate() {
    if (!isPromptValid) return

    dispatchSetIsGenerating(true)
    setGenerationError(null)

    try {
      const categorySlugs = [
        "technology",
        "music",
        "art-design",
        "sports",
        "food-drink",
        "business",
        "health-wellness",
        "education",
        "social-community",
        "gaming",
      ]

      const result = await generateFromPrompt({ prompt: promptText, categorySlugs })

      if (result.error) {
        toast.error(result.message ?? "AI generation failed. Please try again.")
        setGenerationError(result.message ?? "Something went wrong.")
        return
      }

      dispatchSetGeneratedData(result.data)
    } catch {
      toast.error("AI generation failed. Please try again.")
      setGenerationError("Something went wrong.")
    } finally {
      dispatchSetIsGenerating(false)
    }
  }

  function handleUseGenerated() {
    if (!generatedData) return

    dispatchUpdateWizardData({
      title: generatedData.title,
      description: generatedData.description,
      category: generatedData.category,
      tags: generatedData.tags,
    })
    dispatchSetWizardStep("details")
  }

  function handleRegenerate() {
    dispatchSetGeneratedData(null)
    setGenerationError(null)
  }

  function handleSkip() {
    dispatchSetWizardStep("details")
  }

  if (generatedData && !isGenerating) {
    return (
      <div className="space-y-6">
        <div className="space-y-2 text-center">
          <Sparkles className="mx-auto size-8 text-primary" />
          <h2 className="text-xl font-semibold">AI Generated Your Event</h2>
          <p className="text-sm text-muted-foreground">
            Review the generated details below. You can edit everything in the next step.
          </p>
        </div>

        <div className="space-y-4 rounded-lg border bg-accent p-4 text-sm">
          <div>
            <span className="font-medium text-muted-foreground">Title</span>
            <p className="mt-1 font-semibold">{generatedData.title}</p>
          </div>
          <div>
            <span className="font-medium text-muted-foreground">Description</span>
            <p className="mt-1 text-muted-foreground">{generatedData.description}</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">{generatedData.category}</Badge>
            {generatedData.tags.map(tag => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        </div>

        <p className="text-center text-xs text-muted-foreground">
          Generated by AI — feel free to edit in the next step.
        </p>

        <div className="flex gap-3">
          <Button variant="outline" className="flex-1" onClick={handleRegenerate}>
            <RefreshCw className="mr-2 size-4" />
            Regenerate
          </Button>
          <Button className="flex-1" onClick={handleUseGenerated}>
            Use This
            <ArrowRight className="ml-2 size-4" />
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="space-y-2 text-center">
        <Sparkles className="mx-auto size-8 text-primary" />
        <h2 className="text-xl font-semibold">Describe Your Event</h2>
        <p className="text-sm text-muted-foreground">Tell us about your event and AI will help you set it up.</p>
      </div>

      <div className="space-y-2">
        <Textarea
          placeholder="e.g., A weekend tech conference in San Francisco about AI and machine learning with 200 attendees..."
          className="min-h-32"
          value={promptText}
          maxLength={PROMPT_MAX_LENGTH}
          onChange={e => setPromptText(e.target.value)}
        />
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>
            {charCount < PROMPT_MIN_LENGTH
              ? `At least ${PROMPT_MIN_LENGTH} characters required`
              : `${charCount}/${PROMPT_MAX_LENGTH} characters`}
          </span>
          <Button variant="link" className="h-auto p-0 text-xs" onClick={handleSkip}>
            Skip AI
            <SkipForward className="ml-1 size-3" />
          </Button>
        </div>
      </div>

      {generationError ? <p className="text-center text-sm text-destructive">{generationError}</p> : null}

      <Button className="w-full" disabled={!isPromptValid || isGenerating} onClick={handleGenerate}>
        {isGenerating ? (
          <>
            <Loader2 className="mr-2 size-4 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="mr-2 size-4" />
            Generate with AI
          </>
        )}
      </Button>
    </div>
  )
}
